image: eclipse-temurin:17-jdk

stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .m2/repository
    - .sonar/cache


.test-templete : &test-templete
  stage: test
  script:
    - |
        if [ ${MAVEN_DEBUG} == "true" ]; then
          export MAVEN_CLI_OPTS="${MAVEN_CLI_OPTS} -e -X"
        fi
    - ./mvnw -U clean $MAVEN_CLI_OPTS test -Dgpg.skip=true
    - ./mvnw ossindex:audit

.build-template: &build-template
  stage: build
  before_script:
    - apt-get update && apt-get install -y gnupg2
    - export GPG_TTY=$(tty)
    - echo "${GPG_PRI}" | gpg --batch --import
    - |
      if [ ${MAVEN_DEBUG} == "true" ]; then
        export MAVEN_CLI_OPTS="${MAVEN_CLI_OPTS} -e -X"
      fi
  script:
    - ./mvnw -U clean $MAVEN_CLI_OPTS deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -s settings.xml
    - ./mvnw ossindex:audit
    

build-snapshot:
  <<: *build-template
  tags:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - "*.md"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"

      
build-release :
  <<: *build-template
  only:
    - "/^*.release$/"


